<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Provinsi;
use App\Models\Kabupaten;

class KabupatenSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['kode' => '11.01', 'provinsi' => 'Aceh', 'nama' => 'Aceh Selatan'],
            ['kode' => '11.02', 'provinsi' => 'Aceh', 'nama' => 'Aceh Tenggara'],
            ['kode' => '11.03', 'provinsi' => 'Aceh', 'nama' => 'Aceh Timur'],
            ['kode' => '11.04', 'provinsi' => 'Aceh', 'nama' => 'Aceh Tengah'],
            ['kode' => '11.05', 'provinsi' => 'Aceh', 'nama' => 'Aceh Barat'],
            ['kode' => '11.06', 'provinsi' => 'Aceh', 'nama' => 'Aceh Besar'],
            ['kode' => '11.07', 'provinsi' => 'Aceh', 'nama' => 'Pidie'],
            ['kode' => '11.08', 'provinsi' => 'Aceh', 'nama' => 'Aceh Utara'],
            ['kode' => '11.09', 'provinsi' => 'Aceh', 'nama' => 'Simeulue'],
            ['kode' => '11.10', 'provinsi' => 'Aceh', 'nama' => 'Aceh Singkil'],
            ['kode' => '11.11', 'provinsi' => 'Aceh', 'nama' => 'Bireuen'],
            ['kode' => '11.12', 'provinsi' => 'Aceh', 'nama' => 'Aceh Barat Daya'],
            ['kode' => '11.13', 'provinsi' => 'Aceh', 'nama' => 'Gayo Lues'],
            ['kode' => '11.14', 'provinsi' => 'Aceh', 'nama' => 'Aceh Jaya'],
            ['kode' => '11.15', 'provinsi' => 'Aceh', 'nama' => 'Nagan Raya'],
            ['kode' => '11.16', 'provinsi' => 'Aceh', 'nama' => 'Aceh Tamiang'],
            ['kode' => '11.17', 'provinsi' => 'Aceh', 'nama' => 'Bener Meriah'],
            ['kode' => '11.18', 'provinsi' => 'Aceh', 'nama' => 'Pidie Jaya'],
            ['kode' => '12.01', 'provinsi' => 'Sumatera Utara', 'nama' => 'Tapanuli Tengah'],
            ['kode' => '12.02', 'provinsi' => 'Sumatera Utara', 'nama' => 'Tapanuli Utara'],
            ['kode' => '12.03', 'provinsi' => 'Sumatera Utara', 'nama' => 'Tapanuli Selatan'],
            ['kode' => '12.04', 'provinsi' => 'Sumatera Utara', 'nama' => 'Nias'],
            ['kode' => '12.05', 'provinsi' => 'Sumatera Utara', 'nama' => 'Langkat'],
            ['kode' => '12.06', 'provinsi' => 'Sumatera Utara', 'nama' => 'Karo'],
            ['kode' => '12.07', 'provinsi' => 'Sumatera Utara', 'nama' => 'Deli Serdang'],
            ['kode' => '12.08', 'provinsi' => 'Sumatera Utara', 'nama' => 'Simalungun'],
            ['kode' => '12.09', 'provinsi' => 'Sumatera Utara', 'nama' => 'Asahan'],
            ['kode' => '12.10', 'provinsi' => 'Sumatera Utara', 'nama' => 'Labuhanbatu'],
            ['kode' => '12.11', 'provinsi' => 'Sumatera Utara', 'nama' => 'Dairi'],
            ['kode' => '12.12', 'provinsi' => 'Sumatera Utara', 'nama' => 'Toba'],
            ['kode' => '12.13', 'provinsi' => 'Sumatera Utara', 'nama' => 'Mandailing Natal'],
            ['kode' => '12.14', 'provinsi' => 'Sumatera Utara', 'nama' => 'Nias Selatan'],
            ['kode' => '12.15', 'provinsi' => 'Sumatera Utara', 'nama' => 'Pakpak Bharat'],
            ['kode' => '12.16', 'provinsi' => 'Sumatera Utara', 'nama' => 'Humbang Hasundutan'],
            ['kode' => '12.17', 'provinsi' => 'Sumatera Utara', 'nama' => 'Samosir'],
            ['kode' => '12.18', 'provinsi' => 'Sumatera Utara', 'nama' => 'Serdang Bedagai'],
            ['kode' => '12.19', 'provinsi' => 'Sumatera Utara', 'nama' => 'Batu Bara'],
            ['kode' => '12.20', 'provinsi' => 'Sumatera Utara', 'nama' => 'Padang Lawas Utara'],
            ['kode' => '12.21', 'provinsi' => 'Sumatera Utara', 'nama' => 'Padang Lawas'],
            ['kode' => '12.22', 'provinsi' => 'Sumatera Utara', 'nama' => 'Labuhanbatu Selatan'],
            ['kode' => '12.23', 'provinsi' => 'Sumatera Utara', 'nama' => 'Labuhanbatu Utara'],
            ['kode' => '12.24', 'provinsi' => 'Sumatera Utara', 'nama' => 'Nias Utara'],
            ['kode' => '12.25', 'provinsi' => 'Sumatera Utara', 'nama' => 'Nias Barat'],
            ['kode' => '13.01', 'provinsi' => 'Sumatera Barat', 'nama' => 'Pesisir Selatan'],
            ['kode' => '13.02', 'provinsi' => 'Sumatera Barat', 'nama' => 'Solok'],
            ['kode' => '13.03', 'provinsi' => 'Sumatera Barat', 'nama' => 'Sijunjung'],
            ['kode' => '13.04', 'provinsi' => 'Sumatera Barat', 'nama' => 'Tanah Datar'],
            ['kode' => '13.05', 'provinsi' => 'Sumatera Barat', 'nama' => 'Padang Pariaman'],
            ['kode' => '13.06', 'provinsi' => 'Sumatera Barat', 'nama' => 'Agam'],
            ['kode' => '13.07', 'provinsi' => 'Sumatera Barat', 'nama' => 'Lima Puluh Kota'],
            ['kode' => '13.08', 'provinsi' => 'Sumatera Barat', 'nama' => 'Pasaman'],
            ['kode' => '13.09', 'provinsi' => 'Sumatera Barat', 'nama' => 'Kepulauan Mentawai'],
            ['kode' => '13.10', 'provinsi' => 'Sumatera Barat', 'nama' => 'Dharmasraya'],
            ['kode' => '13.11', 'provinsi' => 'Sumatera Barat', 'nama' => 'Solok Selatan'],
            ['kode' => '13.12', 'provinsi' => 'Sumatera Barat', 'nama' => 'Pasaman Barat'],
            ['kode' => '14.01', 'provinsi' => 'Riau', 'nama' => 'Kampar'],
            ['kode' => '14.02', 'provinsi' => 'Riau', 'nama' => 'Indragiri Hulu'],
            ['kode' => '14.03', 'provinsi' => 'Riau', 'nama' => 'Bengkalis'],
            ['kode' => '14.04', 'provinsi' => 'Riau', 'nama' => 'Indragiri Hilir'],
            ['kode' => '14.05', 'provinsi' => 'Riau', 'nama' => 'Pelalawan'],
            ['kode' => '14.06', 'provinsi' => 'Riau', 'nama' => 'Rokan Hulu'],
            ['kode' => '14.07', 'provinsi' => 'Riau', 'nama' => 'Rokan Hilir'],
            ['kode' => '14.08', 'provinsi' => 'Riau', 'nama' => 'Siak'],
            ['kode' => '14.09', 'provinsi' => 'Riau', 'nama' => 'Kuantan Singingi'],
            ['kode' => '14.10', 'provinsi' => 'Riau', 'nama' => 'Kepulauan Meranti'],
            ['kode' => '15.01', 'provinsi' => 'Jambi', 'nama' => 'Kerinci'],
            ['kode' => '15.02', 'provinsi' => 'Jambi', 'nama' => 'Merangin'],
            ['kode' => '15.03', 'provinsi' => 'Jambi', 'nama' => 'Sarolangun'],
            ['kode' => '15.04', 'provinsi' => 'Jambi', 'nama' => 'Batanghari'],
            ['kode' => '15.05', 'provinsi' => 'Jambi', 'nama' => 'Muaro Jambi'],
            ['kode' => '15.06', 'provinsi' => 'Jambi', 'nama' => 'Tanjung Jabung Barat'],
            ['kode' => '15.07', 'provinsi' => 'Jambi', 'nama' => 'Tanjung Jabung Timur'],
            ['kode' => '15.08', 'provinsi' => 'Jambi', 'nama' => 'Bungo'],
            ['kode' => '15.09', 'provinsi' => 'Jambi', 'nama' => 'Tebo'],
            ['kode' => '16.01', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Ogan Komering Ulu'],
            ['kode' => '16.02', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Ogan Komering Ilir'],
            ['kode' => '16.03', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Muara Enim'],
            ['kode' => '16.04', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Lahat'],
            ['kode' => '16.05', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Musi Rawas'],
            ['kode' => '16.06', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Musi Banyuasin'],
            ['kode' => '16.07', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Banyuasin'],
            ['kode' => '16.08', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Ogan Komering Ulu Timur'],
            ['kode' => '16.09', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Ogan Komering Ulu Selatan'],
            ['kode' => '16.10', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Ogan Ilir'],
            ['kode' => '16.11', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Empat Lawang'],
            ['kode' => '16.12', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Penukal Abab Lematang Ilir'],
            ['kode' => '16.13', 'provinsi' => 'Sumatera Selatan', 'nama' => 'Musi Rawas Utara'],
            ['kode' => '17.01', 'provinsi' => 'Bengkulu', 'nama' => 'Bengkulu Selatan'],
            ['kode' => '17.02', 'provinsi' => 'Bengkulu', 'nama' => 'Rejang Lebong'],
            ['kode' => '17.03', 'provinsi' => 'Bengkulu', 'nama' => 'Bengkulu Utara'],
            ['kode' => '17.04', 'provinsi' => 'Bengkulu', 'nama' => 'Kaur'],
            ['kode' => '17.05', 'provinsi' => 'Bengkulu', 'nama' => 'Seluma'],
            ['kode' => '17.06', 'provinsi' => 'Bengkulu', 'nama' => 'Muko-Muko'],
            ['kode' => '17.07', 'provinsi' => 'Bengkulu', 'nama' => 'Lebong'],
            ['kode' => '17.08', 'provinsi' => 'Bengkulu', 'nama' => 'Kepahiang'],
            ['kode' => '17.09', 'provinsi' => 'Bengkulu', 'nama' => 'Bengkulu Tengah'],
            ['kode' => '18.01', 'provinsi' => 'Lampung', 'nama' => 'Lampung Selatan'],
            ['kode' => '18.02', 'provinsi' => 'Lampung', 'nama' => 'Lampung Tengah'],
            ['kode' => '18.03', 'provinsi' => 'Lampung', 'nama' => 'Lampung Utara'],
            ['kode' => '18.04', 'provinsi' => 'Lampung', 'nama' => 'Lampung Barat'],
            ['kode' => '18.05', 'provinsi' => 'Lampung', 'nama' => 'Tulang Bawang'],
            ['kode' => '18.06', 'provinsi' => 'Lampung', 'nama' => 'Tanggamus'],
            ['kode' => '18.07', 'provinsi' => 'Lampung', 'nama' => 'Lampung Timur'],
            ['kode' => '18.08', 'provinsi' => 'Lampung', 'nama' => 'Way Kanan'],
            ['kode' => '18.09', 'provinsi' => 'Lampung', 'nama' => 'Pesawaran'],
            ['kode' => '18.10', 'provinsi' => 'Lampung', 'nama' => 'Pringsewu'],
            ['kode' => '18.11', 'provinsi' => 'Lampung', 'nama' => 'Mesuji'],
            ['kode' => '18.12', 'provinsi' => 'Lampung', 'nama' => 'Tulangbawang Barat'],
            ['kode' => '18.13', 'provinsi' => 'Lampung', 'nama' => 'Pesisir Barat'],
            ['kode' => '19.01', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Bangka'],
            ['kode' => '19.02', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Belitung'],
            ['kode' => '19.03', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Bangka Selatan'],
            ['kode' => '19.04', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Bangka Tengah'],
            ['kode' => '19.05', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Bangka Barat'],
            ['kode' => '19.06', 'provinsi' => 'Kepulauan Bangka Belitung', 'nama' => 'Belitung Timur'],
            ['kode' => '21.01', 'provinsi' => 'Kepulauan Riau', 'nama' => 'Bintan'],
            ['kode' => '21.02', 'provinsi' => 'Kepulauan Riau', 'nama' => 'Karimun'],
            ['kode' => '21.03', 'provinsi' => 'Kepulauan Riau', 'nama' => 'Natuna'],
            ['kode' => '21.04', 'provinsi' => 'Kepulauan Riau', 'nama' => 'Lingga'],
            ['kode' => '21.05', 'provinsi' => 'Kepulauan Riau', 'nama' => 'Kepulauan Anambas'],
            ['kode' => '31.01', 'provinsi' => 'DKI Jakarta', 'nama' => 'Kepulauan Seribu'],
            ['kode' => '32.01', 'provinsi' => 'Jawa Barat', 'nama' => 'Bogor'],
            ['kode' => '32.02', 'provinsi' => 'Jawa Barat', 'nama' => 'Sukabumi'],
            ['kode' => '32.03', 'provinsi' => 'Jawa Barat', 'nama' => 'Cianjur'],
            ['kode' => '32.04', 'provinsi' => 'Jawa Barat', 'nama' => 'Bandung'],
            ['kode' => '32.05', 'provinsi' => 'Jawa Barat', 'nama' => 'Garut'],
            ['kode' => '32.06', 'provinsi' => 'Jawa Barat', 'nama' => 'Tasikmalaya'],
            ['kode' => '32.07', 'provinsi' => 'Jawa Barat', 'nama' => 'Ciamis'],
            ['kode' => '32.08', 'provinsi' => 'Jawa Barat', 'nama' => 'Kuningan'],
            ['kode' => '32.09', 'provinsi' => 'Jawa Barat', 'nama' => 'Cirebon'],
            ['kode' => '32.10', 'provinsi' => 'Jawa Barat', 'nama' => 'Majalengka'],
            ['kode' => '32.11', 'provinsi' => 'Jawa Barat', 'nama' => 'Sumedang'],
            ['kode' => '32.12', 'provinsi' => 'Jawa Barat', 'nama' => 'Indramayu'],
            ['kode' => '32.13', 'provinsi' => 'Jawa Barat', 'nama' => 'Subang'],
            ['kode' => '32.14', 'provinsi' => 'Jawa Barat', 'nama' => 'Purwakarta'],
            ['kode' => '32.15', 'provinsi' => 'Jawa Barat', 'nama' => 'Karawang'],
            ['kode' => '32.16', 'provinsi' => 'Jawa Barat', 'nama' => 'Bekasi'],
            ['kode' => '32.17', 'provinsi' => 'Jawa Barat', 'nama' => 'Bandung Barat'],
            ['kode' => '32.18', 'provinsi' => 'Jawa Barat', 'nama' => 'Pangandaran'],
            ['kode' => '33.01', 'provinsi' => 'Jawa Tengah', 'nama' => 'Cilacap'],
            ['kode' => '33.02', 'provinsi' => 'Jawa Tengah', 'nama' => 'Banyumas'],
            ['kode' => '33.03', 'provinsi' => 'Jawa Tengah', 'nama' => 'Purbalingga'],
            ['kode' => '33.04', 'provinsi' => 'Jawa Tengah', 'nama' => 'Banjarnegara'],
            ['kode' => '33.05', 'provinsi' => 'Jawa Tengah', 'nama' => 'Kebumen'],
            ['kode' => '33.06', 'provinsi' => 'Jawa Tengah', 'nama' => 'Purworejo'],
            ['kode' => '33.07', 'provinsi' => 'Jawa Tengah', 'nama' => 'Wonosobo'],
            ['kode' => '33.08', 'provinsi' => 'Jawa Tengah', 'nama' => 'Magelang'],
            ['kode' => '33.09', 'provinsi' => 'Jawa Tengah', 'nama' => 'Boyolali'],
            ['kode' => '33.10', 'provinsi' => 'Jawa Tengah', 'nama' => 'Klaten'],
            ['kode' => '33.11', 'provinsi' => 'Jawa Tengah', 'nama' => 'Sukoharjo'],
            ['kode' => '33.12', 'provinsi' => 'Jawa Tengah', 'nama' => 'Wonogiri'],
            ['kode' => '33.13', 'provinsi' => 'Jawa Tengah', 'nama' => 'Karanganyar'],
            ['kode' => '33.14', 'provinsi' => 'Jawa Tengah', 'nama' => 'Sragen'],
            ['kode' => '33.15', 'provinsi' => 'Jawa Tengah', 'nama' => 'Grobogan'],
            ['kode' => '33.16', 'provinsi' => 'Jawa Tengah', 'nama' => 'Blora'],
            ['kode' => '33.17', 'provinsi' => 'Jawa Tengah', 'nama' => 'Rembang'],
            ['kode' => '33.18', 'provinsi' => 'Jawa Tengah', 'nama' => 'Pati'],
            ['kode' => '33.19', 'provinsi' => 'Jawa Tengah', 'nama' => 'Kudus'],
            ['kode' => '33.20', 'provinsi' => 'Jawa Tengah', 'nama' => 'Jepara'],
            ['kode' => '33.21', 'provinsi' => 'Jawa Tengah', 'nama' => 'Demak'],
            ['kode' => '33.22', 'provinsi' => 'Jawa Tengah', 'nama' => 'Semarang'],
            ['kode' => '33.23', 'provinsi' => 'Jawa Tengah', 'nama' => 'Temanggung'],
            ['kode' => '33.24', 'provinsi' => 'Jawa Tengah', 'nama' => 'Kendal'],
            ['kode' => '33.25', 'provinsi' => 'Jawa Tengah', 'nama' => 'Batang'],
            ['kode' => '33.26', 'provinsi' => 'Jawa Tengah', 'nama' => 'Pekalongan'],
            ['kode' => '33.27', 'provinsi' => 'Jawa Tengah', 'nama' => 'Pemalang'],
            ['kode' => '33.28', 'provinsi' => 'Jawa Tengah', 'nama' => 'Tegal'],
            ['kode' => '33.29', 'provinsi' => 'Jawa Tengah', 'nama' => 'Brebes'],
            ['kode' => '34.01', 'provinsi' => 'DI Yogyakarta', 'nama' => 'Kulon Progo'],
            ['kode' => '34.02', 'provinsi' => 'DI Yogyakarta', 'nama' => 'Bantul'],
            ['kode' => '34.03', 'provinsi' => 'DI Yogyakarta', 'nama' => 'Gunungkidul'],
            ['kode' => '34.04', 'provinsi' => 'DI Yogyakarta', 'nama' => 'Sleman'],
            ['kode' => '35.01', 'provinsi' => 'Jawa Timur', 'nama' => 'Pacitan'],
            ['kode' => '35.02', 'provinsi' => 'Jawa Timur', 'nama' => 'Ponorogo'],
            ['kode' => '35.03', 'provinsi' => 'Jawa Timur', 'nama' => 'Trenggalek'],
            ['kode' => '35.04', 'provinsi' => 'Jawa Timur', 'nama' => 'Tulungagung'],
            ['kode' => '35.05', 'provinsi' => 'Jawa Timur', 'nama' => 'Blitar'],
            ['kode' => '35.06', 'provinsi' => 'Jawa Timur', 'nama' => 'Kediri'],
            ['kode' => '35.07', 'provinsi' => 'Jawa Timur', 'nama' => 'Malang'],
            ['kode' => '35.08', 'provinsi' => 'Jawa Timur', 'nama' => 'Lumajang'],
            ['kode' => '35.09', 'provinsi' => 'Jawa Timur', 'nama' => 'Jember'],
            ['kode' => '35.10', 'provinsi' => 'Jawa Timur', 'nama' => 'Banyuwangi'],
            ['kode' => '35.11', 'provinsi' => 'Jawa Timur', 'nama' => 'Bondowoso'],
            ['kode' => '35.12', 'provinsi' => 'Jawa Timur', 'nama' => 'Situbondo'],
            ['kode' => '35.13', 'provinsi' => 'Jawa Timur', 'nama' => 'Probolinggo'],
            ['kode' => '35.14', 'provinsi' => 'Jawa Timur', 'nama' => 'Pasuruan'],
            ['kode' => '35.15', 'provinsi' => 'Jawa Timur', 'nama' => 'Sidoarjo'],
            ['kode' => '35.16', 'provinsi' => 'Jawa Timur', 'nama' => 'Mojokerto'],
            ['kode' => '35.17', 'provinsi' => 'Jawa Timur', 'nama' => 'Jombang'],
            ['kode' => '35.18', 'provinsi' => 'Jawa Timur', 'nama' => 'Nganjuk'],
            ['kode' => '35.19', 'provinsi' => 'Jawa Timur', 'nama' => 'Madiun'],
            ['kode' => '35.20', 'provinsi' => 'Jawa Timur', 'nama' => 'Magetan'],
            ['kode' => '35.21', 'provinsi' => 'Jawa Timur', 'nama' => 'Ngawi'],
            ['kode' => '35.22', 'provinsi' => 'Jawa Timur', 'nama' => 'Bojonegoro'],
            ['kode' => '35.23', 'provinsi' => 'Jawa Timur', 'nama' => 'Tuban'],
            ['kode' => '35.24', 'provinsi' => 'Jawa Timur', 'nama' => 'Lamongan'],
            ['kode' => '35.25', 'provinsi' => 'Jawa Timur', 'nama' => 'Gresik'],
            ['kode' => '35.26', 'provinsi' => 'Jawa Timur', 'nama' => 'Bangkalan'],
            ['kode' => '35.27', 'provinsi' => 'Jawa Timur', 'nama' => 'Sampang'],
            ['kode' => '35.28', 'provinsi' => 'Jawa Timur', 'nama' => 'Pamekasan'],
            ['kode' => '35.29', 'provinsi' => 'Jawa Timur', 'nama' => 'Sumenep'],
            ['kode' => '36.01', 'provinsi' => 'Banten', 'nama' => 'Pandeglang'],
            ['kode' => '36.02', 'provinsi' => 'Banten', 'nama' => 'Lebak'],
            ['kode' => '36.03', 'provinsi' => 'Banten', 'nama' => 'Tangerang'],
            ['kode' => '36.04', 'provinsi' => 'Banten', 'nama' => 'Serang'],
            ['kode' => '51.01', 'provinsi' => 'Bali', 'nama' => 'Jembrana'],
            ['kode' => '51.02', 'provinsi' => 'Bali', 'nama' => 'Tabanan'],
            ['kode' => '51.03', 'provinsi' => 'Bali', 'nama' => 'Badung'],
            ['kode' => '51.04', 'provinsi' => 'Bali', 'nama' => 'Gianyar'],
            ['kode' => '51.05', 'provinsi' => 'Bali', 'nama' => 'Klungkung'],
            ['kode' => '51.06', 'provinsi' => 'Bali', 'nama' => 'Bangli'],
            ['kode' => '51.07', 'provinsi' => 'Bali', 'nama' => 'Karangasem'],
            ['kode' => '51.08', 'provinsi' => 'Bali', 'nama' => 'Buleleng'],
            ['kode' => '52.01', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Lombok Barat'],
            ['kode' => '52.02', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Lombok Tengah'],
            ['kode' => '52.03', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Lombok Timur'],
            ['kode' => '52.04', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Sumbawa'],
            ['kode' => '52.05', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Dompu'],
            ['kode' => '52.06', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Bima'],
            ['kode' => '52.07', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Sumbawa Barat'],
            ['kode' => '52.08', 'provinsi' => 'Nusa Tenggara Barat', 'nama' => 'Lombok Utara'],
            ['kode' => '53.01', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Kupang'],
            ['kode' => '53.02', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Timor Tengah Selatan'],
            ['kode' => '53.03', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Timor Tengah Utara'],
            ['kode' => '53.04', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Belu'],
            ['kode' => '53.05', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Alor'],
            ['kode' => '53.06', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Flores Timur'],
            ['kode' => '53.07', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sikka'],
            ['kode' => '53.08', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Ende'],
            ['kode' => '53.09', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Ngada'],
            ['kode' => '53.10', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Manggarai'],
            ['kode' => '53.11', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sumba Timur'],
            ['kode' => '53.12', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sumba Barat'],
            ['kode' => '53.13', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Lembata'],
            ['kode' => '53.14', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Rote Ndao'],
            ['kode' => '53.15', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Manggarai Barat'],
            ['kode' => '53.16', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Nagekeo'],
            ['kode' => '53.17', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sumba Tengah'],
            ['kode' => '53.18', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sumba Barat Daya'],
            ['kode' => '53.19', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Manggarai Timur'],
            ['kode' => '53.20', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Sabu Raijua'],
            ['kode' => '53.21', 'provinsi' => 'Nusa Tenggara Timur', 'nama' => 'Malaka'],
            ['kode' => '61.01', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Sambas'],
            ['kode' => '61.02', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Mempawah'],
            ['kode' => '61.03', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Sanggau'],
            ['kode' => '61.04', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Ketapang'],
            ['kode' => '61.05', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Sintang'],
            ['kode' => '61.06', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Kapuas Hulu'],
            ['kode' => '61.07', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Bengkayang'],
            ['kode' => '61.08', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Landak'],
            ['kode' => '61.09', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Sekadau'],
            ['kode' => '61.10', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Melawi'],
            ['kode' => '61.11', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Kayong Utara'],
            ['kode' => '61.12', 'provinsi' => 'Kalimantan Barat', 'nama' => 'Kubu Raya'],
            ['kode' => '62.01', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Kotawaringin Barat'],
            ['kode' => '62.02', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Kotawaringin Timur'],
            ['kode' => '62.03', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Kapuas'],
            ['kode' => '62.04', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Barito Selatan'],
            ['kode' => '62.05', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Barito Utara'],
            ['kode' => '62.06', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Katingan'],
            ['kode' => '62.07', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Seruyan'],
            ['kode' => '62.08', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Sukamara'],
            ['kode' => '62.09', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Lamandau'],
            ['kode' => '62.10', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Gunung Mas'],
            ['kode' => '62.11', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Pulang Pisau'],
            ['kode' => '62.12', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Murung Raya'],
            ['kode' => '62.13', 'provinsi' => 'Kalimantan Tengah', 'nama' => 'Barito Timur'],
            ['kode' => '63.01', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Tanah Laut'],
            ['kode' => '63.02', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Kotabaru'],
            ['kode' => '63.03', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Banjar Baru'],
            ['kode' => '63.04', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Barito Kuala'],
            ['kode' => '63.05', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Tapin'],
            ['kode' => '63.06', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Hulu Sungai Selatan'],
            ['kode' => '63.07', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Hulu Sungai Tengah'],
            ['kode' => '63.08', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Hulu Sungai Utara'],
            ['kode' => '63.09', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Tabalong'],
            ['kode' => '63.10', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Tanah Bumbu'],
            ['kode' => '63.11', 'provinsi' => 'Kalimantan Selatan', 'nama' => 'Balangan'],
            ['kode' => '64.01', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Paser'],
            ['kode' => '64.02', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Kutai Kartanegara'],
            ['kode' => '64.03', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Berau'],
            ['kode' => '64.04', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Kutai Barat'],
            ['kode' => '64.05', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Kutai Timur'],
            ['kode' => '64.06', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Penajam Paser Utara'],
            ['kode' => '64.07', 'provinsi' => 'Kalimantan Timur', 'nama' => 'Mahakam Ulu'],
            ['kode' => '65.01', 'provinsi' => 'Kalimantan Utara', 'nama' => 'Bulungan'],
            ['kode' => '65.02', 'provinsi' => 'Kalimantan Utara', 'nama' => 'Malinau'],
            ['kode' => '65.03', 'provinsi' => 'Kalimantan Utara', 'nama' => 'Nunukan'],
            ['kode' => '65.04', 'provinsi' => 'Kalimantan Utara', 'nama' => 'Tana Tidung'],
            ['kode' => '71.01', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Bolaang Mongondow'],
            ['kode' => '71.02', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Minahasa'],
            ['kode' => '71.03', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Kepulauan Sangihe'],
            ['kode' => '71.04', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Kepulauan Talaud'],
            ['kode' => '71.05', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Minahasa Selatan'],
            ['kode' => '71.06', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Minahasa Utara'],
            ['kode' => '71.07', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Minahasa Tenggara'],
            ['kode' => '71.08', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Bolaang Mongondow Utara'],
            ['kode' => '71.09', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Kepulauan Siau Tagulandang Biaro'],
            ['kode' => '71.10', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Bolaang Mongondow Timur'],
            ['kode' => '71.11', 'provinsi' => 'Sulawesi Utara', 'nama' => 'Bolaang Mongondow Selatan'],
            ['kode' => '72.01', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Banggai'],
            ['kode' => '72.02', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Poso'],
            ['kode' => '72.03', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Donggala'],
            ['kode' => '72.04', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Toli-Toli'],
            ['kode' => '72.05', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Buol'],
            ['kode' => '72.06', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Morowali'],
            ['kode' => '72.07', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Banggai Kepulauan'],
            ['kode' => '72.08', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Parigi Moutong'],
            ['kode' => '72.09', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Tojo Una-Una'],
            ['kode' => '72.10', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Sigi'],
            ['kode' => '72.11', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Banggai Laut'],
            ['kode' => '72.12', 'provinsi' => 'Sulawesi Tengah', 'nama' => 'Morowali Utara'],
            ['kode' => '73.01', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Kepulauan Selayar'],
            ['kode' => '73.02', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Bulukumba'],
            ['kode' => '73.03', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Bantaeng'],
            ['kode' => '73.04', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Jeneponto'],
            ['kode' => '73.05', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Takalar'],
            ['kode' => '73.06', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Gowa'],
            ['kode' => '73.07', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Sinjai'],
            ['kode' => '73.08', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Bone'],
            ['kode' => '73.09', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Maros'],
            ['kode' => '73.10', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Pangkajene Kepulauan'],
            ['kode' => '73.11', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Barru'],
            ['kode' => '73.12', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Soppeng'],
            ['kode' => '73.13', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Wajo'],
            ['kode' => '73.14', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Sidenreng Rappang'],
            ['kode' => '73.15', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Pinrang'],
            ['kode' => '73.16', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Enrekang'],
            ['kode' => '73.17', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Luwu'],
            ['kode' => '73.18', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Tana Toraja'],
            ['kode' => '73.19', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Luwu Utara'],
            ['kode' => '73.20', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Luwu Timur'],
            ['kode' => '73.21', 'provinsi' => 'Sulawesi Selatan', 'nama' => 'Toraja Utara'],
            ['kode' => '74.01', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Kolaka'],
            ['kode' => '74.02', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Konawe'],
            ['kode' => '74.03', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Muna'],
            ['kode' => '74.04', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Buton'],
            ['kode' => '74.05', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Konawe Selatan'],
            ['kode' => '74.06', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Bombana'],
            ['kode' => '74.07', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Wakatobi'],
            ['kode' => '74.08', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Kolaka Utara'],
            ['kode' => '74.09', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Konawe Utara'],
            ['kode' => '74.10', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Buton Utara'],
            ['kode' => '74.11', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Kolaka Timur'],
            ['kode' => '74.12', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Konawe Kepulauan'],
            ['kode' => '74.13', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Muna Barat'],
            ['kode' => '74.14', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Buton Tengah'],
            ['kode' => '74.15', 'provinsi' => 'Sulawesi Tenggara', 'nama' => 'Buton Selatan'],
            ['kode' => '75.01', 'provinsi' => 'Gorontalo', 'nama' => 'Gorontalo'],
            ['kode' => '75.02', 'provinsi' => 'Gorontalo', 'nama' => 'Boalemo'],
            ['kode' => '75.03', 'provinsi' => 'Gorontalo', 'nama' => 'Bone Bolango'],
            ['kode' => '75.04', 'provinsi' => 'Gorontalo', 'nama' => 'Pohuwato'],
            ['kode' => '75.05', 'provinsi' => 'Gorontalo', 'nama' => 'Gorontalo Utara'],
            ['kode' => '76.01', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Pasangkayu'],
            ['kode' => '76.02', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Mamuju'],
            ['kode' => '76.03', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Mamasa'],
            ['kode' => '76.04', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Majene'],
            ['kode' => '76.05', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Polewali Mandar'],
            ['kode' => '76.06', 'provinsi' => 'Sulawesi Barat', 'nama' => 'Mamuju Tengah'],
            ['kode' => '81.01', 'provinsi' => 'Maluku', 'nama' => 'Maluku Tengah'],
            ['kode' => '81.02', 'provinsi' => 'Maluku', 'nama' => 'Maluku Tenggara'],
            ['kode' => '81.03', 'provinsi' => 'Maluku', 'nama' => 'Kepulauan Tanimbar'],
            ['kode' => '81.04', 'provinsi' => 'Maluku', 'nama' => 'Buru'],
            ['kode' => '81.05', 'provinsi' => 'Maluku', 'nama' => 'Seram Bagian Timur'],
            ['kode' => '81.06', 'provinsi' => 'Maluku', 'nama' => 'Seram Bagian Barat'],
            ['kode' => '81.07', 'provinsi' => 'Maluku', 'nama' => 'Kepulauan Aru'],
            ['kode' => '81.08', 'provinsi' => 'Maluku', 'nama' => 'Maluku Barat Daya'],
            ['kode' => '81.09', 'provinsi' => 'Maluku', 'nama' => 'Buru Selatan'],
            ['kode' => '82.01', 'provinsi' => 'Maluku Utara', 'nama' => 'Halmahera Barat'],
            ['kode' => '82.02', 'provinsi' => 'Maluku Utara', 'nama' => 'Halmahera Tengah'],
            ['kode' => '82.03', 'provinsi' => 'Maluku Utara', 'nama' => 'Halmahera Utara'],
            ['kode' => '82.04', 'provinsi' => 'Maluku Utara', 'nama' => 'Halmahera Selatan'],
            ['kode' => '82.05', 'provinsi' => 'Maluku Utara', 'nama' => 'Kepulauan Sula'],
            ['kode' => '82.06', 'provinsi' => 'Maluku Utara', 'nama' => 'Halmahera Timur'],
            ['kode' => '82.07', 'provinsi' => 'Maluku Utara', 'nama' => 'Pulau Morotai'],
            ['kode' => '82.08', 'provinsi' => 'Maluku Utara', 'nama' => 'Pulau Taliabu'],
            ['kode' => '91.01', 'provinsi' => 'Papua', 'nama' => 'Merauke'],
            ['kode' => '91.02', 'provinsi' => 'Papua', 'nama' => 'Jayawijaya'],
            ['kode' => '91.03', 'provinsi' => 'Papua', 'nama' => 'Jayapura'],
            ['kode' => '91.04', 'provinsi' => 'Papua', 'nama' => 'Nabire'],
            ['kode' => '91.05', 'provinsi' => 'Papua', 'nama' => 'Kepulauan Yapen'],
            ['kode' => '91.06', 'provinsi' => 'Papua', 'nama' => 'Biak Numfor'],
            ['kode' => '91.07', 'provinsi' => 'Papua', 'nama' => 'Puncak Jaya'],
            ['kode' => '91.08', 'provinsi' => 'Papua', 'nama' => 'Paniai'],
            ['kode' => '91.09', 'provinsi' => 'Papua', 'nama' => 'Mimika'],
            ['kode' => '91.10', 'provinsi' => 'Papua', 'nama' => 'Sarmi'],
            ['kode' => '91.11', 'provinsi' => 'Papua', 'nama' => 'Keerom'],
            ['kode' => '91.12', 'provinsi' => 'Papua', 'nama' => 'Pegunungan Bintang'],
            ['kode' => '91.13', 'provinsi' => 'Papua', 'nama' => 'Yahukimo'],
            ['kode' => '91.14', 'provinsi' => 'Papua', 'nama' => 'Tolikara'],
            ['kode' => '91.15', 'provinsi' => 'Papua', 'nama' => 'Waropen'],
            ['kode' => '91.16', 'provinsi' => 'Papua', 'nama' => 'Boven Digoel'],
            ['kode' => '91.17', 'provinsi' => 'Papua', 'nama' => 'Mappi'],
            ['kode' => '91.18', 'provinsi' => 'Papua', 'nama' => 'Asmat'],
            ['kode' => '91.19', 'provinsi' => 'Papua', 'nama' => 'Supiori'],
            ['kode' => '91.20', 'provinsi' => 'Papua', 'nama' => 'Mamberamo Raya'],
            ['kode' => '91.21', 'provinsi' => 'Papua', 'nama' => 'Mamberamo Tengah'],
            ['kode' => '91.22', 'provinsi' => 'Papua', 'nama' => 'Yalimo'],
            ['kode' => '91.23', 'provinsi' => 'Papua', 'nama' => 'Lanny Jaya'],
            ['kode' => '91.24', 'provinsi' => 'Papua', 'nama' => 'Nduga'],
            ['kode' => '91.25', 'provinsi' => 'Papua', 'nama' => 'Puncak'],
            ['kode' => '91.26', 'provinsi' => 'Papua', 'nama' => 'Dogiyai'],
            ['kode' => '91.27', 'provinsi' => 'Papua', 'nama' => 'Intan Jaya'],
            ['kode' => '91.28', 'provinsi' => 'Papua', 'nama' => 'Deiyai'],
            ['kode' => '92.01', 'provinsi' => 'Papua Barat', 'nama' => 'Sorong'],
            ['kode' => '92.02', 'provinsi' => 'Papua Barat', 'nama' => 'Manokwari'],
            ['kode' => '92.03', 'provinsi' => 'Papua Barat', 'nama' => 'Fak Fak'],
            ['kode' => '92.04', 'provinsi' => 'Papua Barat', 'nama' => 'Sorong Selatan'],
            ['kode' => '92.05', 'provinsi' => 'Papua Barat', 'nama' => 'Raja Ampat'],
            ['kode' => '92.06', 'provinsi' => 'Papua Barat', 'nama' => 'Teluk Bintuni'],
            ['kode' => '92.07', 'provinsi' => 'Papua Barat', 'nama' => 'Teluk Wondama'],
            ['kode' => '92.08', 'provinsi' => 'Papua Barat', 'nama' => 'Kaimana'],
            ['kode' => '92.09', 'provinsi' => 'Papua Barat', 'nama' => 'Tambrauw'],
            ['kode' => '92.10', 'provinsi' => 'Papua Barat', 'nama' => 'Maybrat'],
            ['kode' => '92.11', 'provinsi' => 'Papua Barat', 'nama' => 'Manokwari Selatan'],
            ['kode' => '92.12', 'provinsi' => 'Papua Barat', 'nama' => 'Pegunungan Arfak'],
        ];

        foreach ($data as $item) {
            $provinsi = Provinsi::where('nama_provinsi', $item['provinsi'])->first();

            if (!$provinsi) {
                $this->command->warn(
                    "Provinsi tidak ditemukan: {$item['provinsi']} (kode {$item['kode']})"
                    );
                continue;
            }

            Kabupaten::firstOrCreate([
                'provinsi_id' => $provinsi->id,
                'nama_kabupaten' => $item['nama'],
            ]);
        }

        $this->command->info(
            'Import kabupaten selesai: ' . count($data) . ' data diproses.'
        );
    }
}